# fly.toml app configuration file generated for source-be-staging on 2025-07-08T14:36:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'source-be-staging'
primary_region = 'jnb'

[build]

[env]
  CORS_ORIGIN = 'http://localhost:3001'
  ENV = 'prod'
  GOOGLE_CLIENT_ID = '449412212863-h1rre1gdmfgq96jt160fdd30bfatjiqb.apps.googleusercontent.com'
  DATABASE_DIR = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = 'source_storage_staging'
  destination = '/data'
  processes = ['app']
  initial_size = '50gb'
