name: Prod Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Prod
    runs-on: self-hosted
    #concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - name: Execute deploy script
        run: cd ~/Developer/source-be-deploy && ./deploy.sh
