name: Prod Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/deploy/source-be
            git checkout main
            git pull
            ./build.sh
            sudo /bin/systemctl restart source-be
